/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adamasmaca;

/**
 *
 * @author msı
 */
public class SifreEkran extends javax.swing.JFrame {
    private int yanlisSayisi = 0;
    private boolean belirlemeModuMu;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SifreEkran.class.getName());

    /**
     * Creates new form SifreEkran
     */
    public SifreEkran() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(20, 20, 35));

lblBaslik.setForeground(new java.awt.Color(255, 210, 60));
lblBaslik.setBackground(new java.awt.Color(30, 30, 52));
lblBaslik.setOpaque(true);

lblSifre.setForeground(java.awt.Color.WHITE);
lblTekrar.setForeground(java.awt.Color.WHITE);

lblHata.setForeground(new java.awt.Color(255, 90, 90));

txtSifre1.setBackground(new java.awt.Color(40, 40, 65));
txtSifre1.setForeground(java.awt.Color.WHITE);
txtSifre1.setCaretColor(java.awt.Color.WHITE);

txtSifre2.setBackground(new java.awt.Color(40, 40, 65));
txtSifre2.setForeground(java.awt.Color.WHITE);
txtSifre2.setCaretColor(java.awt.Color.WHITE);

btnGiris.setBackground(new java.awt.Color(28, 130, 28));
btnGiris.setForeground(java.awt.Color.WHITE);

this.setSize(400, 320);
this.setLocationRelativeTo(null);
this.setTitle("Adam Asmaca - Giriş");
        DosyaYonetici.klasorleriOlustur();
        DosyaYonetici.dosyayiTemizle(DosyaYonetici.KELIMELER_GECMIS);
DosyaYonetici.kelimelerOlustur();
belirlemeModuMu = !DosyaYonetici.sifreVarMi();

if (belirlemeModuMu) {
    lblBaslik.setText("İlk Kullanım — Şifre Belirleyin");
    btnGiris.setText("Şifreyi Kaydet");
    lblSifre.setText("Şifre:");
    lblTekrar.setText("Tekrar:");
} else {
    lblBaslik.setText("Adam Asmaca — Giriş");
    btnGiris.setText("Giriş Yap");
    lblTekrar.setVisible(false);
    txtSifre2.setVisible(false);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBaslik = new javax.swing.JLabel();
        lblSifre = new javax.swing.JLabel();
        txtSifre1 = new javax.swing.JPasswordField();
        lblTekrar = new javax.swing.JLabel();
        txtSifre2 = new javax.swing.JPasswordField();
        btnGiris = new javax.swing.JButton();
        lblHata = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));

        lblBaslik.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblBaslik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaslik.setText("Adam Asmaca - Giriş");

        lblSifre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSifre.setText("Şifre : ");

        txtSifre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSifre1.setToolTipText("");
        txtSifre1.addActionListener(this::txtSifre1ActionPerformed);

        lblTekrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTekrar.setText("Tekrar : ");

        txtSifre2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSifre2.addActionListener(this::txtSifre2ActionPerformed);

        btnGiris.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGiris.setText("Giriş Yap ");
        btnGiris.addActionListener(this::btnGirisActionPerformed);

        lblHata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTekrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSifre1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtSifre2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnGiris))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHata, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifre)
                    .addComponent(txtSifre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTekrar)
                    .addComponent(txtSifre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnGiris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHata, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        // TODO add your handling code here:
        if (belirlemeModuMu) {
    sifreBelirle();
} else {
    sifreGiris();
}
    }
   private void sifreBelirle() {
    String s1 = new String(txtSifre1.getPassword()).trim();
    String s2 = new String(txtSifre2.getPassword()).trim();
    if (s1.isEmpty()) { lblHata.setText("Şifre boş olamaz!"); return; }
    if (!s1.equals(s2)) { lblHata.setText("Şifreler eşleşmiyor!"); return; }

    String ipucu = javax.swing.JOptionPane.showInputDialog(this, 
        "Şifrenizi unutursanız diye bir ipucu yazın:", 
        "İpucu Belirle", 
        javax.swing.JOptionPane.QUESTION_MESSAGE);
        
    if (ipucu == null || ipucu.trim().isEmpty()) {
        ipucu = "İpucu belirtilmemiş.";
    }
    
    DosyaYonetici.dosyayaYaz(DosyaYonetici.TXT_KLASOR + "\\ipucu.txt", ipucu);
    DosyaYonetici.sifreKaydet(s1);
    DosyaYonetici.logKaydet("Şifre Belirlendi");
    javax.swing.JOptionPane.showMessageDialog(this, "Şifre ve İpucu başarıyla kaydedildi!");
    oyunuAc();
}

private void sifreGiris() {
    String girilen = new String(txtSifre1.getPassword()).trim();
    String kayitli = DosyaYonetici.sifreOku();
    
    if (girilen.equals(kayitli)) {
        DosyaYonetici.logKaydet("Başarılı Giriş");
        oyunuAc();
    } else {
        yanlisSayisi++;
        DosyaYonetici.logKaydet("Hatalı Giriş (" + yanlisSayisi + ". deneme)");
        txtSifre1.setText("");

        java.util.List<String> ipucuSatirlari = DosyaYonetici.dosyaOku(DosyaYonetici.TXT_KLASOR + "\\ipucu.txt");
        String ipucuMetni = ipucuSatirlari.isEmpty() ? "İpucu bulunamadı." : ipucuSatirlari.get(0);

        if (yanlisSayisi >= 3) {
            javax.swing.JOptionPane.showMessageDialog(this, "3 hatalı giriş! Program kapanıyor.", "Sistem Kilitlendi", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else {
            lblHata.setText("Kalan hak: " + (3 - yanlisSayisi));
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Hatalı şifre!\n\nŞifre İpucunuz: " + ipucuMetni, 
                "İpucu", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }
}
private void oyunuAc() {
    new OyunEkran().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnGirisActionPerformed

    private void txtSifre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifre1ActionPerformed
        // TODO add your handling code here:
        if (belirlemeModuMu) {
    sifreBelirle();
} else {
    sifreGiris();
}
    }//GEN-LAST:event_txtSifre1ActionPerformed

    private void txtSifre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifre2ActionPerformed
        // TODO add your handling code here:
        sifreBelirle();
    }//GEN-LAST:event_txtSifre2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SifreEkran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JLabel lblBaslik;
    private javax.swing.JLabel lblHata;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JLabel lblTekrar;
    private javax.swing.JPasswordField txtSifre1;
    private javax.swing.JPasswordField txtSifre2;
    // End of variables declaration//GEN-END:variables
}
